import type { Metadata } from "next";
import { Inter, Noto_Serif, Pacifico, Source_Code_Pro } from "next/font/google";
import "./globals.css";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const noto = Noto_Serif({
    variable: "--font-noto",
    subsets: ["latin"],
});

const source_code = Source_Code_Pro({
    variable: "--font-source-cod",
    subsets: ["latin"],
});

const pacifico = Pacifico({
    variable: "--font-pacifico",
    weight: ["400"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Notes App",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: "/logo.png", type: "image/png" },
            { url: "/logo.svg", type: "image/svg+xml" },
        ],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${noto.variable} ${source_code.variable} ${pacifico.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
